### ISSUE TITLE
iWalker-Info.plist looks to be missing

### ISSUE THREAD

**Issue by alanwill** [kevicebryan/NC2-iWalker#1]
Getting a compile error that the file is missing and it's showing up as red in Xcode

**Comment by alanwill** [comment]
I deleted the reference to the file in the Build Settings and that got rid of the build issues.

Thanks so much for sharing this example with us, it's really helpful as I try to learn HealthKit and SwiftUI 🙏🏼

**Comment by kevicebryan** [comment]
Your welcome, and thanks for stopping by! 👋

**Comment by kevicebryan** [comment]
> I deleted the reference to the file in the Build Settings and that got rid of the build issues.
> 
> Thanks so much for sharing this example with us, it's really helpful as I try to learn HealthKit and SwiftUI 🙏🏼

No problem, and thanks for stopping by 😁!

**Comment by zjavaid1981** [comment]
How do you remove it from build settings?

**Comment by zjavaid1981** [comment]
> I deleted the reference to the file in the Build Settings and that got rid of the build issues.
> 
> Thanks so much for sharing this example with us, it's really helpful as I try to learn HealthKit and SwiftUI 🙏🏼

Can you plz explain how?

**Comment by alanwill** [comment]
If you go to the Project Settings page screen, you should see a Build Settings tab there.
